### ISSUE TITLE
Overlay without lower/upper mounts?

### ISSUE THREAD

**Issue by ryansturmer** [bluerider/liveroot#11]
Question - when using your hook in its "raw" mode - I see the overlay once the system is booted, but I don't see the underlying mounts.  Shouldn't /lroot and /troot/upper and /troot/work be visible to me?

This hook seems to work really well for me, thanks for authoring it!

**Comment by bluerider** [comment]
/lroot and /troot appear in the initramfs. You chroot into /new_root; hence you don't see /lroot and /troot.

**Comment by ryansturmer** [comment]
Of course!  derp.
