### ISSUE TITLE
rm -r in overlay_flush?

### ISSUE THREAD

**Issue by louis-ad** [bluerider/liveroot#14]
Looking at the overlay_flush script, these 2 lines worry me:
           umount /run/oroot;
           rm -r /run/oroot;

if the unmounting fails for whatever reason... the script deletes your mounted "root" filesystem. That sounds like it's very safe!

**Comment by bluerider** [comment]
I guess I could replace ";' with "&&". This would ensure the directory wouldn't be removed if unmounts failed.

**Comment by bluerider** [comment]
Issue fixed with be50c417a57d7dffd73511086581f023e393b892
